# # import pytest
# #
# # from selenium import webdriver
# #
# # @pytest.fixture()
# # def driver():
# #     driver = webdriver.Chrome()
# #     yield driver
# #
# # def test_open_url_verfy_titile(driver):
# #     driver.get("https://courses.lawpreptutorial.com/")
# #     print(driver.title)
# #     assert "Law-Prep-Tutorial" == driver.title
# #
#
# # Generated by Selenium IDE
# import pytest
# import time
# import json
# from selenium import webdriver
# from selenium.webdriver.common.by import By
# from selenium.webdriver.common.action_chains import ActionChains
# from selenium.webdriver.support import expected_conditions
# from selenium.webdriver.support.wait import WebDriverWait
# from selenium.webdriver.common.keys import Keys
# from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
#
#
# class TestHomepage():
#     def setup_method(self, method):
#         self.driver = webdriver.Chrome()
#         self.vars = {}
#
#     def teardown_method(self, method):
#         self.driver.quit()
#
#     def test_homepage(self):
#         self.driver.get("https://courses.lawpreptutorial.com/")
#         self.driver.set_window_size(945, 1020)
#         element = self.driver.find_element(By.LINK_TEXT, "CLAT 2024: Online Coaching Program (12th Passed/Appearing)")
#         actions = ActionChains(self.driver)
#         actions.move_to_element(element).perform()
#         element = self.driver.find_element(By.CSS_SELECTOR, "body")
#         actions = ActionChains(self.driver)
#         actions.move_to_element(element, 0, 0).perform()
#         self.driver.find_element(By.LINK_TEXT, "Login").click()
#         self.driver.find_element(By.ID, "mobile_number").click()
#         self.driver.find_element(By.ID, "mobile_number").send_keys("8559933187")
#         self.driver.find_element(By.ID, "password").click()
#         self.driver.find_element(By.ID, "password").send_keys("123456")
#         self.driver.find_element(By.CSS_SELECTOR, ".btn-submit").click()
#         element = self.driver.find_element(By.CSS_SELECTOR, ".btn-submit")
#         actions = ActionChains(self.driver)
#         actions.move_to_element(element).perform()
#         element = self.driver.find_element(By.CSS_SELECTOR, "body")
#         actions = ActionChains(self.driver)
#         actions.move_to_element(element, 0, 0).perform()


# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestLogin():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_login(self):
        self.driver.get("https://courses.lawpreptutorial.com/")
        self.driver.set_window_size(1936, 1056)
        self.driver.find_element(By.LINK_TEXT, "Go To Home").click()
        self.driver.find_element(By.CSS_SELECTOR, ".name").click()
        self.driver.find_element(By.LINK_TEXT, "Dashboard").click()
        self.driver.find_element(By.CSS_SELECTOR, "#\\__BVID__311__BV_toggle_ > .name").click()
        self.driver.find_element(By.CSS_SELECTOR, ".show > li:nth-child(1) > .dropdown-item").click()

